name: dump1090
services:
  dump1090:
    container_name: dump1090
    image: dump1090:alpine
    restart: unless-stopped
    init: true
    ports: 
        - 8080:8080
    devices:
      - /dev/bus/usb
    environment:
      RECEIVER_LON: "-106.0"
      RECEIVER_LAT: "35.0"
      RECEIVER: "rtlsdr"
      RECEIVER_SERIAL: "your device s/n here."
      JSON_LOCATION_ACCURACY: 2
