
name: piaware
services:
  dump1090:
    container_name: dump1090
    image: dump1090:alpine
    restart: unless-stopped
    init: true
    ports: 
        - 8080:8080
    devices:
      - /dev/bus/usb
    environment:
      RECEIVER_LON: "-106.51992"
      RECEIVER_LAT: "35.05850"
      RECEIVER: "rtlsdr"
      RECEIVER_SERIAL: "00000978"
      JSON_LOCATION_ACCURACY: 2
